/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author acere
 */
public class MenuGUI extends javax.swing.JFrame {

    /**
     * Creates new form MenuGUI
     */
    public MenuGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bTSocio = new javax.swing.JButton();
        bTSalasSquash = new javax.swing.JButton();
        bTReservas = new javax.swing.JButton();
        bTProcuarReservas = new javax.swing.JButton();
        bTMonitores = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bTSocio.setText("Socios");
        bTSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTSocioActionPerformed(evt);
            }
        });

        bTSalasSquash.setText("Salas de squash");
        bTSalasSquash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTSalasSquashActionPerformed(evt);
            }
        });

        bTReservas.setText("Reservas");
        bTReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTReservasActionPerformed(evt);
            }
        });

        bTProcuarReservas.setText("Procurar reservas");
        bTProcuarReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTProcuarReservasActionPerformed(evt);
            }
        });

        bTMonitores.setText("Monitores");
        bTMonitores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTMonitoresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bTSalasSquash, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bTSocio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bTReservas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bTProcuarReservas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bTMonitores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(bTSocio, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bTSalasSquash, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bTReservas, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bTProcuarReservas, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bTMonitores, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bTSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTSocioActionPerformed
        SocioGUI socio = new SocioGUI();
        socio.setDefaultCloseOperation(SocioGUI.DISPOSE_ON_CLOSE);
        socio.setVisible(true);
    }//GEN-LAST:event_bTSocioActionPerformed

    private void bTSalasSquashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTSalasSquashActionPerformed
        SalasSquashGUI squash = new SalasSquashGUI();
        squash.setDefaultCloseOperation(SalasSquashGUI.DISPOSE_ON_CLOSE);
        squash.setVisible(true);
    }//GEN-LAST:event_bTSalasSquashActionPerformed

    private void bTReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTReservasActionPerformed
        ReservasGUI reservas = new ReservasGUI();
        reservas.setDefaultCloseOperation(ReservasGUI.DISPOSE_ON_CLOSE);
        reservas.setVisible(true);
    }//GEN-LAST:event_bTReservasActionPerformed

    private void bTProcuarReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTProcuarReservasActionPerformed
        ReservasSocioGUI reservasSocio = new ReservasSocioGUI();
        reservasSocio.setDefaultCloseOperation(ReservasSocioGUI.DISPOSE_ON_CLOSE);
        reservasSocio.setVisible(true);
    }//GEN-LAST:event_bTProcuarReservasActionPerformed

    private void bTMonitoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTMonitoresActionPerformed
        MonitorGUI monitor = new MonitorGUI();
        monitor.setDefaultCloseOperation(MonitorGUI.DISPOSE_ON_CLOSE);
        monitor.setVisible(true);
    }//GEN-LAST:event_bTMonitoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bTMonitores;
    private javax.swing.JButton bTProcuarReservas;
    private javax.swing.JButton bTReservas;
    private javax.swing.JButton bTSalasSquash;
    private javax.swing.JButton bTSocio;
    // End of variables declaration//GEN-END:variables
}
