/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;
import modelo.Reserva;
import java.util.ArrayList;
import dao.FabricaConexao;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import dao.ReservasSocioDAO;
import modelo.Socio;

/**
 *
 * @author acere
 */
public class ReservasSocioGUI extends javax.swing.JFrame {

    /**
     * Creates new form ReservasSocio
     */
    public ReservasSocioGUI() {
        initComponents();
        atualizaEstadoComboBox();
    }
    
    public void mostra_reserva(ArrayList<Reserva> lista) {
        DefaultTableModel model = (DefaultTableModel)tabelaReserva.getModel();
        Object[] row = new Object[3];
        for(int i = 0; i < lista.size(); i++) {
            row[0] = lista.get(i).getNroSocio();
            row[1] = lista.get(i).getNroSala();
            row[2] = lista.get(i).getDataReserva();
            model.addRow(row);
        }
    }
    
    protected void atualizaEstadoComboBox() {
        boolean ativaNome = cBBuscaForma.getSelectedItem().equals("Nome");
        if(ativaNome) {
            tFNome.setEnabled(true);
            tFNroSocio.setEnabled(false);
        } 
        else {
            tFNome.setEnabled(false);
            tFNroSocio.setEnabled(true);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tFNome = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaReserva = new javax.swing.JTable();
        bTBuscar = new javax.swing.JButton();
        tFNroSocio = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        bTLimpa = new javax.swing.JButton();
        cBBuscaForma = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nome:");

        tFNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tFNomeActionPerformed(evt);
            }
        });

        tabelaReserva.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NroSocio", "NroSala", "Data reserva"
            }
        ));
        jScrollPane1.setViewportView(tabelaReserva);

        bTBuscar.setText("Buscar");
        bTBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTBuscarActionPerformed(evt);
            }
        });

        tFNroSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tFNroSocioActionPerformed(evt);
            }
        });

        jLabel2.setText("Número Socio:");

        bTLimpa.setText("Limpar");
        bTLimpa.setToolTipText("");
        bTLimpa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTLimpaActionPerformed(evt);
            }
        });

        cBBuscaForma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nome", "Número" }));
        cBBuscaForma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBBuscaFormaActionPerformed(evt);
            }
        });

        jLabel3.setText("Forma de busca: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tFNome, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cBBuscaForma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tFNroSocio, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(bTBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bTLimpa, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)))
                .addGap(45, 45, 45)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cBBuscaForma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tFNroSocio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tFNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bTBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bTLimpa, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(140, 140, 140))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tFNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tFNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tFNomeActionPerformed

    private void tFNroSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tFNroSocioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tFNroSocioActionPerformed

    private void bTBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTBuscarActionPerformed
        if(tFNroSocio.getText().equals("") && tFNome.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha o campo para buscar informações.");
            return;
        }

        try{
            ArrayList<Reserva> reservas;
            ReservasSocioDAO bd = new ReservasSocioDAO();
            
            if(cBBuscaForma.getSelectedItem().equals("Nome")) {
                Socio socio = new Socio(tFNome.getText());
                reservas = bd.listarReservasPeloNomeSocio(socio);
            }
            else {
                Socio socio = new Socio(Integer.parseInt(tFNroSocio.getText()));
                reservas = bd.listarReservasPeloNroSocio(socio);
            }
            
            DefaultTableModel model = (DefaultTableModel)tabelaReserva.getModel();
            model.setRowCount(0);
            
            if(reservas.isEmpty()) {
                JOptionPane.showMessageDialog(null, "O cliente não possui reservas atualmente.");
            }
            else {
                mostra_reserva(reservas);
            }
        }
        catch(SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_bTBuscarActionPerformed

    private void bTLimpaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTLimpaActionPerformed
        tFNroSocio.setText("");
        tFNome.setText("");
    }//GEN-LAST:event_bTLimpaActionPerformed

    private void cBBuscaFormaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBBuscaFormaActionPerformed
        atualizaEstadoComboBox();
    }//GEN-LAST:event_cBBuscaFormaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReservasSocioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReservasSocioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReservasSocioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReservasSocioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReservasSocioGUI().setVisible(true);
            }
        });
    }

    //Objeto de conexão ao BD
    private final FabricaConexao conObj = new FabricaConexao();
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bTBuscar;
    private javax.swing.JButton bTLimpa;
    private javax.swing.JComboBox<String> cBBuscaForma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tFNome;
    private javax.swing.JTextField tFNroSocio;
    private javax.swing.JTable tabelaReserva;
    // End of variables declaration//GEN-END:variables
}
