/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.FabricaConexao;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.SalaSquashCompoundSala;
import dao.SalaSquashCompoundSalaDAO;

/**
 *
 * @author acere
 */
public class SalasSquashGUI extends javax.swing.JFrame {

    /**
     * Creates new form SalasSquashGUI
     */
    public SalasSquashGUI() {
        initComponents();
        fillSalasComboBox();
        mostraSalasSquash();
    }
    
    private void mostraSalasSquash() {
        try{
            SalaSquashCompoundSalaDAO bd = new SalaSquashCompoundSalaDAO();
            ArrayList<SalaSquashCompoundSala> lista = bd.listarSalaSquash();
            DefaultTableModel model = (DefaultTableModel)tabelaSalasSquash.getModel();
            Object[] row = new Object[4];
            for(int i = 0; i < lista.size(); i++) {
                row[0] = lista.get(i).getNroSala();
                row[1] = lista.get(i).getArea();
                row[2] = lista.get(i).getLocalizacao();
                row[3] = lista.get(i).getEstado();
                model.addRow(row);
            }
        }
        catch(SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private int[] createSalasRange(ArrayList<Integer> blackList, int salasMaxRange) {
        int[] salasRange = new int[salasMaxRange + 5];
        
        int i = 1;
        int elementsInSalasRange = 0;
        while(true) {
            salasRange[elementsInSalasRange] = i;
            elementsInSalasRange++;
            i++;
            if(elementsInSalasRange == salasRange.length)
                break;
        }
        
        return salasRange;
    }
    
    private void fillSalasComboBox() {          
        try{
            int salasMaxRange = 1;
            SalaSquashCompoundSalaDAO bd = new SalaSquashCompoundSalaDAO();
            
            ArrayList<Integer> blackList = bd.blackList();
            salasMaxRange = bd.salasMaxRange();
            
            int[] salasRange = createSalasRange(blackList, salasMaxRange);
        
            cBSalas.removeAllItems();
            for(int i = 0; i < salasRange.length; i++) {
                cBSalas.addItem(salasRange[i]+"");
            }
        }
        catch(SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private void recarregaSalasSquash() {
        DefaultTableModel model = (DefaultTableModel)tabelaSalasSquash.getModel();
        model.setRowCount(0);
        mostraSalasSquash();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tFLocalizacao = new javax.swing.JTextField();
        tFArea = new javax.swing.JTextField();
        cBSalas = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaSalasSquash = new javax.swing.JTable();
        cBEstado = new javax.swing.JComboBox<>();
        bTInserir = new javax.swing.JButton();
        bTDeletar = new javax.swing.JButton();
        bTRecarregar = new javax.swing.JButton();
        bTLimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Sala: ");

        jLabel2.setText("Area: ");

        jLabel3.setText("Localização: ");

        jLabel5.setText("Estado: ");

        tabelaSalasSquash.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NroSala", "Area", "Localização", "Estado"
            }
        ));
        tabelaSalasSquash.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaSalasSquashMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaSalasSquash);

        cBEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "bom", "ruim" }));

        bTInserir.setText("Inserir");
        bTInserir.setPreferredSize(new java.awt.Dimension(83, 25));
        bTInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTInserirActionPerformed(evt);
            }
        });

        bTDeletar.setText("Deletar");
        bTDeletar.setPreferredSize(new java.awt.Dimension(83, 25));
        bTDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTDeletarActionPerformed(evt);
            }
        });

        bTRecarregar.setText("Recaregar");
        bTRecarregar.setPreferredSize(new java.awt.Dimension(83, 25));
        bTRecarregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTRecarregarActionPerformed(evt);
            }
        });

        bTLimpar.setText("Limpar");
        bTLimpar.setPreferredSize(new java.awt.Dimension(83, 25));
        bTLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cBSalas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cBEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tFArea, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                            .addComponent(tFLocalizacao)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bTRecarregar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bTLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bTInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(bTDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cBSalas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tFArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tFLocalizacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cBEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bTInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bTDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bTRecarregar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bTLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bTInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTInserirActionPerformed
        if(tFArea.getText().equals("") || tFLocalizacao.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos para inserir uma nova sala.");
            return;
        }
        
        try{
            SalaSquashCompoundSalaDAO bd = new SalaSquashCompoundSalaDAO();            
            SalaSquashCompoundSala sala = new SalaSquashCompoundSala(Integer.parseInt(cBSalas.getSelectedItem().toString()), Float.parseFloat(tFArea.getText()), tFLocalizacao.getText(), cBEstado.getSelectedItem().toString());
            bd.inserirSalaSquash(sala);
            JOptionPane.showMessageDialog(null, "Operação feita com sucesso!");
            recarregaSalasSquash();
        }
        catch(SQLException e) {
            JOptionPane.showMessageDialog(null, e); 
        }                     
    }//GEN-LAST:event_bTInserirActionPerformed

    private void bTDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTDeletarActionPerformed
        int response = JOptionPane.showConfirmDialog(null, "You tem certeza que deseja deletar a sala " + cBSalas.getSelectedItem() + "?", "WARNING", JOptionPane.YES_NO_OPTION);
        
        if (response == JOptionPane.YES_OPTION) {           
            try {
                SalaSquashCompoundSalaDAO bd = new SalaSquashCompoundSalaDAO();
                SalaSquashCompoundSala sala = new SalaSquashCompoundSala(Integer.parseInt(cBSalas.getSelectedItem().toString()));
                bd.deletarSalaSquash(sala);                
                JOptionPane.showMessageDialog(null, "Operação feita com sucesso!");
                recarregaSalasSquash();
            }
            catch(SQLException e) {
                JOptionPane.showMessageDialog(null, e); 
            }
        }        
    }//GEN-LAST:event_bTDeletarActionPerformed

    private void bTRecarregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTRecarregarActionPerformed
        recarregaSalasSquash();
        fillSalasComboBox();
    }//GEN-LAST:event_bTRecarregarActionPerformed

    private void bTLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTLimparActionPerformed
        tFArea.setText("");
        tFLocalizacao.setText("");
    }//GEN-LAST:event_bTLimparActionPerformed

    private void tabelaSalasSquashMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaSalasSquashMouseClicked
        DefaultTableModel model = (DefaultTableModel)tabelaSalasSquash.getModel();
        int tableRowIndex = tabelaSalasSquash.getSelectedRow();
        
        cBSalas.setSelectedItem(model.getValueAt(tableRowIndex, 0).toString());
        tFArea.setText(model.getValueAt(tableRowIndex, 1).toString());
        tFLocalizacao.setText(model.getValueAt(tableRowIndex, 2).toString());
        cBEstado.setSelectedItem(model.getValueAt(tableRowIndex, 3).toString());
    }//GEN-LAST:event_tabelaSalasSquashMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SalasSquashGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SalasSquashGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SalasSquashGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SalasSquashGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SalasSquashGUI().setVisible(true);
            }
        });
    }

    //Objeto de conexão ao BD
    private final FabricaConexao conObj = new FabricaConexao();
    //Tipo da sala
    final char tipoSala = 's';
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bTDeletar;
    private javax.swing.JButton bTInserir;
    private javax.swing.JButton bTLimpar;
    private javax.swing.JButton bTRecarregar;
    private javax.swing.JComboBox<String> cBEstado;
    private javax.swing.JComboBox<String> cBSalas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tFArea;
    private javax.swing.JTextField tFLocalizacao;
    private javax.swing.JTable tabelaSalasSquash;
    // End of variables declaration//GEN-END:variables
}
