/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;
import modelo.Socio;
import java.util.ArrayList;
import dao.FabricaConexao;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import dao.SocioDAO;

/**
 *
 * @author acere
 */
public class SocioGUI extends javax.swing.JFrame {

    /**
     * Creates new form SocioGUI
     */
    public SocioGUI() {
        initComponents();
        mostra_socio();
    }
    
    private void mostra_socio() {
        try{
            SocioDAO bd = new SocioDAO();
            ArrayList<Socio> lista = bd.listarSocios();
            DefaultTableModel model = (DefaultTableModel)tabelaSocio.getModel();
            Object[] row = new Object[6];
            for(int i = 0; i < lista.size(); i++) {
                row[0] = lista.get(i).getNroSocio();
                row[1] = lista.get(i).getNome();
                row[2] = lista.get(i).getTelefone();
                row[3] = lista.get(i).getEndereco();
                row[4] = lista.get(i).getProfissao();
                row[5] = lista.get(i).getDocBancarios();
                model.addRow(row);
            }
        }
        catch(SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private void recarrega_socio() {
        DefaultTableModel model = (DefaultTableModel)tabelaSocio.getModel();
        model.setRowCount(0);
        mostra_socio();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tFCodSocio = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tFNome = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tFTelefone = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tFProfissao = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaSocio = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tAEndereco = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        tADocBanco = new javax.swing.JTextArea();
        bTsalva = new javax.swing.JButton();
        bTrecarrega = new javax.swing.JButton();
        bTlimpa = new javax.swing.JButton();
        bTdeleta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Número Socio:");

        tFCodSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tFCodSocioActionPerformed(evt);
            }
        });

        jLabel6.setText("Nome:");

        tFNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tFNomeActionPerformed(evt);
            }
        });

        jLabel7.setText("Telefone: ");

        tFTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tFTelefoneActionPerformed(evt);
            }
        });

        jLabel8.setText("Endereço: ");

        jLabel9.setText("Profissão:");

        tFProfissao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tFProfissaoActionPerformed(evt);
            }
        });

        jLabel10.setText("Dados Bancarios: ");

        tabelaSocio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NroSocio", "Nome", "Telefone", "Endereço", "Profissão", "DocBancarios"
            }
        ));
        tabelaSocio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaSocioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaSocio);

        tAEndereco.setColumns(20);
        tAEndereco.setRows(5);
        jScrollPane2.setViewportView(tAEndereco);

        tADocBanco.setColumns(20);
        tADocBanco.setRows(5);
        jScrollPane3.setViewportView(tADocBanco);

        bTsalva.setText("Salvar");
        bTsalva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTsalvaActionPerformed(evt);
            }
        });

        bTrecarrega.setText("Recarregar");
        bTrecarrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTrecarregaActionPerformed(evt);
            }
        });

        bTlimpa.setText("Limpar");
        bTlimpa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTlimpaActionPerformed(evt);
            }
        });

        bTdeleta.setText("Deletar");
        bTdeleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTdeletaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tFCodSocio, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tFNome, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                                .addComponent(tFTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tFProfissao)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bTrecarrega, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                            .addComponent(bTsalva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bTdeleta, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bTlimpa, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(44, 44, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 714, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tFCodSocio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tFNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tFTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tFProfissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bTdeleta, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bTsalva, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bTrecarrega, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bTlimpa, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(63, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tFCodSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tFCodSocioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tFCodSocioActionPerformed

    private void tFNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tFNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tFNomeActionPerformed

    private void tFTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tFTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tFTelefoneActionPerformed

    private void tFProfissaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tFProfissaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tFProfissaoActionPerformed

    private void bTsalvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTsalvaActionPerformed
        if("".equals(tFTelefone.getText()) || "".equals(tFProfissao.getText()) || "".equals(tFNome.getText()) || "".equals(tFCodSocio.getText()) || "".equals(tAEndereco.getText()) || "".equals(tADocBanco.getText())) {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos para enviar informações.");
            return;
        }
        
        try{
            SocioDAO bd = new SocioDAO();
            Socio socio = new Socio(Integer.parseInt(tFCodSocio.getText()), tFNome.getText(), tFTelefone.getText(), tAEndereco.getText(), tFProfissao.getText(), tADocBanco.getText());
            bd.inserirSocio(socio);
            JOptionPane.showMessageDialog(null, "Operação feita com sucesso!");
            recarrega_socio();
        }
        catch(SQLException e) {
            JOptionPane.showMessageDialog(null, e); 
        }
    }//GEN-LAST:event_bTsalvaActionPerformed

    private void bTrecarregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTrecarregaActionPerformed
        recarrega_socio();
    }//GEN-LAST:event_bTrecarregaActionPerformed

    private void bTlimpaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTlimpaActionPerformed
        tFCodSocio.setText("");
        tFNome.setText("");
        tFTelefone.setText("");
        tAEndereco.setText("");
        tFProfissao.setText("");
        tADocBanco.setText("");
    }//GEN-LAST:event_bTlimpaActionPerformed

    private void bTdeletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTdeletaActionPerformed
        int result = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja realizar essa operação?", null, JOptionPane.YES_OPTION);
         
        if(result == JOptionPane.YES_OPTION) {            
            try {
                SocioDAO bd = new SocioDAO();
                Socio socio = new Socio(Integer.parseInt(tFCodSocio.getText()));
                bd.deletarSocio(socio);
                JOptionPane.showMessageDialog(null, "Operação feita com sucesso!");
                recarrega_socio();
            }
            catch(SQLException e) {
                JOptionPane.showMessageDialog(null, e); 
            }     
        }
    }//GEN-LAST:event_bTdeletaActionPerformed

    private void tabelaSocioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaSocioMouseClicked
        DefaultTableModel model = (DefaultTableModel)tabelaSocio.getModel();
        int tableRowIndex = tabelaSocio.getSelectedRow();
        
        tFCodSocio.setText(model.getValueAt(tableRowIndex, 0).toString());
        tFNome.setText(model.getValueAt(tableRowIndex, 1).toString());
        tFTelefone.setText(model.getValueAt(tableRowIndex, 2).toString());
        tAEndereco.setText(model.getValueAt(tableRowIndex, 3).toString());
        tFProfissao.setText(model.getValueAt(tableRowIndex, 4).toString());
        tADocBanco.setText(model.getValueAt(tableRowIndex, 5).toString());
    }//GEN-LAST:event_tabelaSocioMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SocioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SocioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SocioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SocioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SocioGUI().setVisible(true);
            }
        });
    }

    //Objeto de conexão ao BD
    private final FabricaConexao conObj = new FabricaConexao();
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bTdeleta;
    private javax.swing.JButton bTlimpa;
    private javax.swing.JButton bTrecarrega;
    private javax.swing.JButton bTsalva;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea tADocBanco;
    private javax.swing.JTextArea tAEndereco;
    private javax.swing.JTextField tFCodSocio;
    private javax.swing.JTextField tFNome;
    private javax.swing.JTextField tFProfissao;
    private javax.swing.JTextField tFTelefone;
    private javax.swing.JTable tabelaSocio;
    // End of variables declaration//GEN-END:variables
}
